### ISSUE TITLE
 one of the uplinks is down, refuse to publish

### ISSUE THREAD

**Issue by gywbd** [rlidwka/sinopia#124]
i used to install sinopia and it worked very well. i published a few private npm packages to it, all of them were published successfully. but now when i create a new local package and use "npm publish" to publish to sinopia. it was not ok. but if i republish the old package, it still worked. here is the log from sinopia server:

 warn  --- Server is listening on http://0.0.0.0:4873/
 http  --> ERR, req: 'GET https://registry.npmjs.org/local-version-number', error: CERT_NOT_YET_VALID
 http  <-- 503, user: admin, req: 'PUT /local-version-number', error: one of the uplinks is down, refuse to publish
 http  --> ERR, req: 'GET https://registry.npmjs.org/local-version-number', error: CERT_NOT_YET_VALID
 http  <-- 503, user: admin, req: 'PUT /local-version-number', error: one of the uplinks is down, refuse to publish
 warn  --> host registry.npmjs.org is now offline
 http  <-- 503, user: admin, req: 'PUT /local-version-number', error: one of the uplinks is down, refuse to publish
 http  <-- 201, user: admin, req: 'PUT /local-cache', bytes: 3125/33
 http  <-- 503, user: admin, req: 'PUT /local-version-number', error: one of the uplinks is down, refuse to publish

local-cache is the old package which was published before. and local-version-number is the new package which could not be published. 

i checked the package.json and don't get any error. so can you tell what the problem is? 

thanks!

**Comment by alallier** [comment]
I am receiving this error when trying to publish a local npm package, system time is the correct year
