### ISSUE TITLE
Cannot install the mongodb module

### ISSUE THREAD

**Issue by peecky** [rlidwka/sinopia#150]
Today I try to install the mongodb module vi sinopia, but it fails while it try to install the dependent package mongodb-core@1.0.3.

```
npm ERR! Error: shasum check failed for .../mongodb-core/-/mongodb-core-1.0.3.tgz
npm ERR! Expected: 387649e432368dcd02c983f39454700d6958619a
npm ERR! Actual:   ad459d6f2464d7bf474fde829795da3b515c4c76
```

I deleted storage/mongodb-core directory in my sinopia server, then try again, but it still fails.

The mongodb-core-1.0.3.tgz file stored in my sinopia server is 23963 bytes. But the actual file  http://registry.npmjs.org/mongodb-core/-/mongodb-core-1.0.3.tgz is 64923 bytes.

**Comment by Levino** [comment]
@peecky How did you solve it in the end?

**Comment by peecky** [comment]
@Levino I used previous version until the next version of 1.0.3 released.
