### ISSUE TITLE
listen to only some ports?

### ISSUE THREAD

**Issue by 90christian** [rlidwka/sinopia#172]
Hi,

is it possible to listen to a range of ports or maybe to two specific ports with sinopia?

Thanks

**Comment by lschans** [comment]
I found out after some reverse enginering that you can specify this in the config.yaml using: 
listen: server:port

It would be nice if this feature was better documented.

**Comment by rlidwka** [comment]
@lschans, it is [documented](https://github.com/rlidwka/sinopia/blob/0a38a704fe0801359cefbbd2945ba1840585d3fc/conf/full.yaml#L82-L84) in the full config file. And it's kinda standard to omit host in the unix world anyway.

However, sinopia can't listen to two ports at the same time how. That's a legitimate feature request.

**Comment by rlidwka** [comment]
Fixed in `sinopia@1.1.0`. Now you can specify multiple ports in the config file like [that](https://github.com/rlidwka/sinopia/blob/a55dc6577574c883be5c026e0e1ed14f85d528a3/conf/full.yaml#L88-L93).
