### ISSUE TITLE
Download package failed after sinopia config registry

### ISSUE THREAD

**Issue by boudoury** [rlidwka/sinopia#19]
I start with install sinopia version 0.4.3 and it finish well.Then, I configured the registry as: npm set registry http://localhost:4873/
So after that I tried to download some package and it didn't work and i have got that;

C:\Users\tuto>npm install grunt
npm http GET http://localhost:4873/grunt
npm http 407 http://localhost:4873/grunt
npm ERR! TypeError: Cannot call method 'match' of undefined
npm ERR! at RegClient. (C:\Program Files\nodejs\node_modules\npm\
node_modules\npm-registry-client\lib\request.js:119:29)
npm ERR! at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-re
gistry-client\lib\request.js:158:9)
npm ERR! at RegClient. (C:\Program Files\nodejs\node_modules\npm\
node_modules\npm-registry-client\lib\request.js:252:14)
npm ERR! at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\
node_modules\request\request.js:129:22)
npm ERR! at Request.EventEmitter.emit (events.js:98:17)
npm ERR! at Request. (C:\Program Files\nodejs\node_modules\npm\no
de_modules\request\request.js:873:14)
npm ERR! at Request.EventEmitter.emit (events.js:117:20)
npm ERR! at IncomingMessage. (C:\Program Files\nodejs\node_module
s\npm\node_modules\request\request.js:824:12)
npm ERR! at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR! at streamreadable.js:920:16
npm ERR! If you need help, you may report this log at:
npm ERR! http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR! npm-@googlegroups.com

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "grunt"
npm ERR! cwd C:\Users\tuto
npm ERR! node -v v0.10.19
npm ERR! npm -v 1.3.11
npm ERR! type non_object_property_call
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! C:\Users\tutp\npm-debug.log
npm ERR! not ok code 0

So what Iam supposed to do???

**Comment by rlidwka** [comment]
I believe you're behind a proxy, and it's the proxy configuration at fault here. See #254 for details.

I disabled `X-Forwarded-For` if "proxy" is explicitly specified in config/env in https://github.com/rlidwka/sinopia/commit/0d266be9652d6524d085a46dc5d6ed319a35b99e, hope that helps. If you're behind a transparent proxy which reacts strangely to that header, you'd better contact your ISP.
