### ISSUE TITLE
Cannot use proxy to download package via http://registry.npmjs.org/

### ISSUE THREAD

**Issue by rellaguo** [rlidwka/sinopia#190]
Sinopia: 1.0.0-beta.2
npm: 1.4.21
 
I use sinopia for a private repo hosted on my company server  and I need to pass through a proxy to reach http://registry.npmjs.org/. I set proxy in /home/rellaguo/.config/sinopia/config.yaml

http_proxy: http://web-proxy.at.com:8080
https_proxy: http://web-proxy.at.com:8080
no_proxy: localhost,127.0.0.1

Then I run command: npm install diskdb, I get error message:
$ npm install diskdb
npm ERR registry error parsing json
npm ERR registry error parsing json
npm ERR registry error parsing json
npm ERR SyntaxError: Unexpected token <
npm ERR <HTML><HEAD>
npm ERR <TITLE>Network Error</TITLE>
npm ERR </HEAD>
npm ERR <BODY>
npm ERR <FONT face="Helvetica">
npm ERR <big><strong></strong></big><BR>
npm ERR </FONT>
npm ERR <blockquote>
npm ERR <TABLE border=0 cellPadding=1 width="80%">
npm ERR <TR><TD>
npm ERR <FONT face="Helvetica">
npm ERR <big>Network Error (tcp_error)</big>
npm ERR <BR>
npm ERR <BR>
npm ERR </FONT>
npm ERR </TD></TR>
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica">
npm ERR! A communication error occurred: "Operation timed out"
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica">
npm ERR! The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica" SIZE=2>
npm ERR! <BR>
npm ERR! For assistance, contact your network support team.
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! </TABLE>
npm ERR! </blockquote>
npm ERR! </FONT>
npm ERR! </BODY></HTML>
npm ERR! 
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:266:23)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:238:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:938:16
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-71.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "kappa"
npm ERR! cwd /home/rellaguo
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! type unexpected_token
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rellaguo/npm-debug.log
npm ERR! not ok code 0

Then I run command: npm install diskdb -proxy http://web-proxy.at.com:8080 --https-proxy http://web-proxy.at.com:8080, I get error message too:
$ npm install diskdb -proxy http://web-proxy.at.com:8080 --https-proxy http://web-proxy.at.com:8080
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token <
npm ERR! <HTML><HEAD>
npm ERR! <TITLE>Network Error</TITLE>
npm ERR! </HEAD>
npm ERR! <BODY>
npm ERR! <FONT face="Helvetica">
npm ERR! <big><strong></strong></big><BR>
npm ERR! </FONT>
npm ERR! <blockquote>
npm ERR! <TABLE border=0 cellPadding=1 width="80%">
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica">
npm ERR! <big>Network Error (tcp_error)</big>
npm ERR! <BR>
npm ERR! <BR>
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica">
npm ERR! A communication error occurred: "Operation timed out"
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica">
npm ERR! The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica" SIZE=2>
npm ERR! <BR>
npm ERR! For assistance, contact your network support team.
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! </TABLE>
npm ERR! </blockquote>
npm ERR! </FONT>
npm ERR! </BODY></HTML>
npm ERR! 
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:266:23)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:238:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:938:16
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-71.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "diskdb" "-proxy" "http://web-proxy.at.com:8080" "--https-proxy" "http://web-proxy.at.com:8080"
npm ERR! cwd /home/rellaguo
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! type unexpected_token
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rellaguo/npm-debug.log
npm ERR! not ok code 0

My npm configl list:
$npm config ls -l
; cli configs
long = true
registry = "http://localhost:4873/"
user-agent = "npm/1.4.21 node/v0.10.30 linux x64"

; userconfig /home/agilairedev/.npmrc
https-proxy = "http://web-proxy.cce.hp.com:8080/"
proxy = "http://web-proxy.cce.hp.com:8080/"
registry = "http://localhost:4873/"

; default values
always-auth = false
bin-links = true
browser = null
ca = null
cache = "/home/agilairedev/.npm"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
depth = null
description = true
dev = false
editor = "vi"
email = ""
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
globalconfig = "/usr/local/etc/npmrc"
globalignorefile = "/usr/local/etc/npmignore"
group = 500
heading = "npm"
https-proxy = "http://web-proxy.cce.hp.com:8080/"
ignore-scripts = false
init-module = "/home/agilairedev/.npm-init.js"
init.author.email = ""
init.author.name = ""
init.author.url = ""
init.license = "ISC"
json = false
key = null
link = false
local-address = undefined
loglevel = "warn"
; long = false (overridden)
message = "%s"
node-version = "0.10.30"
npat = false
onload-script = null
optional = true
parseable = false
prefix = "/usr/local"
production = false
proprietary-attribs = true
proxy = "http://web-proxy.cce.hp.com:8080/"
rebuild-bundle = true
; registry = "https://registry.npmjs.org/" (overridden)
rollback = true
save = false
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
searchexclude = null
searchopts = ""
searchsort = "name"
shell = "/bin/bash"
shrinkwrap = true
sign-git-tag = false
spin = true
strict-ssl = true
tag = "latest"
tmp = "/tmp"
umask = 2
unicode = true
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "/home/agilairedev/.npmrc"
username = ""
version = false
versions = false
viewer = "man"

My configuration file:

storage: /home/agilairedev/.local/share/sinopia/storage

users:
  admin:
    password: 613a5389aee3a26c462de0172bbb154c6ebeb34a

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: http://registry.npmjs.org/

packages:
  '@*/*':
    allow_access: $all
    allow_publish: $authenticated

  '*':
    allow_access: $all

    allow_publish: $authenticated

    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}

http_proxy: http://web-proxy.at.com:8080
https_proxy: http://web-proxy.at.com:8080
no_proxy: localhost,127.0.0.1

**Comment by rlidwka** [comment]
Please remove all "proxy" configuration from your npm config.

It should work like this:

```
npm -> localhost:4873 -> web-proxy.at.com -> registry.npmjs.org
```

But with your configuration npm tries to connect to sinopia using proxy:

```
npm -> web-proxy.at.com -> localhost:4873 -> ...
```

Which results in network error, because proxy is on the different host, and "localhost:4873" has different meaning for it.

Or add "localhost" to noproxy in npm (I'm not sure how to do this).

**Comment by rellaguo** [comment]
npm -> localhost:4873 -> web-proxy.at.com -> registry.npmjs.org
How to set sinopia to use proxy to connect registry.npmjs.org. You know my host must use proxy to access internet. Thank you!

**Comment by rellaguo** [comment]
Thank you. I resolved it. As you said, I remove all of NPM proxy configuration but keep proxy configuration in sinopia configuration file. Then it is workable.

**Comment by craigmingtaozhang** [comment]
Hi, 

The configuration key here is http_proxy:
http_proxy: anything
While the one in .npmrc is
proxy: anything

Why it's different?

**Comment by rlidwka** [comment]
> Why it's different?

It's named after environment variable called `http_proxy`, which is supported by a lot of unix tools, `curl` for example.

**Comment by harshendra181** [comment]
ok let me explain we have a server 11.11.11.11(os-windows 2012 r2) we hv installed node js on this server.
Now we are trying to install Socket.io by command npm install socket.io -g
we are trying to install from commond promt
we hv set the proxy as http://proxyip:port and strict-ssl as false and registr as http://registry.npms.org/"

kindly let me now if you want any other detail
