### ISSUE TITLE
Block npm adduser

### ISSUE THREAD

**Issue by imjoshholloway** [rlidwka/sinopia#196]
I might be being stupid here but if my repository is publicly accessible over the internet it seems as if someone could just do:

`npm set registry http://npm.mydomian.com/`

and then

`npm adduser --registry npm set registry http://npm.mydomain.com/`

Is there a way to stop this functionality?

**Comment by csulok** [comment]
I use sinopia with the ldap plugin ([sinopia-ldap](https://github.com/rlidwka/sinopia-ldap)) as the only authentication method, and that plugin has no adduser implementation so there's a nice error:

https://github.com/rlidwka/sinopia/blob/master/lib/auth.js#L83

If you're good with htpasswd as the user dictionary, you can probably fork [sinopia-htpasswd](https://github.com/rlidwka/sinopia-htpasswd), configure that as the authentication plugin and remove the adduser methods from it.

**Comment by rlidwka** [comment]
> If you're okay with htpasswd as the user dictionary, you can probably fork sinopia-htpasswd

If you're using `htpasswd` for auth, you can specify `max_users: 0` in its [config](https://github.com/rlidwka/sinopia-htpasswd/blob/master/README.md#config), and it'll reject any new users.

**Comment by rondonjon** [comment]
The documentation says -1
I guess both should work though.

**Comment by rlidwka** [comment]
Documentation says `-1`, because we have a history of `0` working incorrectly. Both should work now.

*closing*
