### ISSUE TITLE
Change host/port

### ISSUE THREAD

**Issue by sebakerckhof** [rlidwka/sinopia#203]
Hello,

I would like to run sinopia not on my localhost, but on another computer I've got standing around. Therefore I'd like to change the host and port sinopia is listening on, is this possible?

**Comment by rlidwka** [comment]
Yes, see [full config file](https://github.com/rlidwka/sinopia/blob/master/conf/full.yaml) example:

```yaml
# you can specify listen address (or simply a port)
listen: localhost:4873
```

**Comment by sebakerckhof** [comment]
Great, thanks!

2015-02-10 14:51 GMT+01:00 Alex Kocharin <notifications@github.com>:
