### ISSUE TITLE
npm shrinkwrap?

### ISSUE THREAD

**Issue by Schniz** [rlidwka/sinopia#204]
The npm shrinkwrap file prevents from downloading and installing sinopia in a closed network situation.
Although i can download the git repo, installing on my machine and then move it, I'd love to use sinopia to download sinopia :smirk:

**Comment by rlidwka** [comment]
Yeah, you're right. Maybe we could remove hostnames from shrinkwrap leaving only versions.

**Comment by iostat42** [comment]
This affects me as well.

**Comment by rlidwka** [comment]
Fixed in `sinopia@1.1.0`, how all urls are removed from shrinkwrap, but not the versions. I hope this will work.
