### ISSUE TITLE
add dist-tags endpoint

### ISSUE THREAD

**Issue by rlidwka** [rlidwka/sinopia#211]
https://github.com/npm/npm-registry-couchapp/pull/221

Needed for `npm dist-tag add|rm|ls`.

**Comment by jedi4ever** [comment]
+1 for this one

**Comment by jakepusateri** [comment]
+1 as well.

**Comment by rlidwka** [comment]
fixed in https://github.com/rlidwka/sinopia/commit/c09d03b20deac9df629509a008e20a3c7b63b132
