### ISSUE TITLE
Request: Allow storage dir to be loaded via environment variable

### ISSUE THREAD

**Issue by jakepusateri** [rlidwka/sinopia#213]
A variable such as SINOPIA_STORAGE_DIR should exist to allow overriding of the storage directory.

**Comment by vernak2539** [comment]
I think you're looking for something like [this](https://github.com/rlidwka/sinopia/blob/master/conf/default.yaml#L10)

**Comment by jakepusateri** [comment]
I'm aware of the config file. It would be nice to have an environment variable override that config so that you can have finer control of development storage location (a temporary build folder) vs production location (a directory with specific permissions/backup/whatnot). A command line argument would also work for this purpose.

**Comment by JohnBruce** [comment]
Yes please!

**Comment by redusek** [comment]
I would also like to see this.  We have a need to make the storage area dynamic based on the local environment.   Allowing the user to use environment variables in the config file would work.
