### ISSUE TITLE
Multiple remote repositories

### ISSUE THREAD

**Issue by arcaartem** [rlidwka/sinopia#222]
Is it possible to provide more than one remote repository for caching? If so do you have examples?

**Comment by rlidwka** [comment]
If you are talking about the [config](https://github.com/rlidwka/sinopia/blob/0a38a704fe0801359cefbbd2945ba1840585d3fc/conf/full.yaml#L62), repository names in there are actually patterns. You can specify `grunt-*` and cache all its plugins.

It this what are you asking, or I misunderstood the question?

**Comment by arcaartem** [comment]
Must have been a "can't brain today, I have the dumb" moment because it didn't occur to me to look at the source code shortly after I post the question!

I know how now, but I was trying to define multiple registries for Sinopia to fall back on but wasn't sure how to define them [here].
(https://github.com/rlidwka/sinopia/blob/848d591f0a46c3c23f1fa6f548e6209ae1e666ed/conf/full.yaml#L31)

Cheers
