### ISSUE TITLE
Feature request - configuration instead of proxy

### ISSUE THREAD

**Issue by agamm** [rlidwka/sinopia#224]
Could you add a feature that will download some predefined (configuration) packages and make them available without having to proxy them manually?

I need this feature because it is a hassle to manually download packages via sinopia by running: npm install for every package I want saved to use later on.

**Comment by rlidwka** [comment]
I'm not sure it fits here. But somebody could create a cli package that will download all necessary stuff.

Maybe this will help: https://github.com/rlidwka/sinopia/issues/79
