### ISSUE TITLE
Support to customize interface

### ISSUE THREAD

**Issue by brunowego** [rlidwka/sinopia#225]
Will be nicer if add support for custom theme.

**Comment by rlidwka** [comment]
We recently added "template" to the config file, so you can use custom one. See https://github.com/rlidwka/sinopia/pull/208 for details. Is it enough to build it?

If you're talking about a multiple built-in themes, then well... pull requests are welcome. :)

**Comment by brunowego** [comment]
Thanks @rlidwka, this feature "template" is exactly I wish.
