### ISSUE TITLE
Memory requirements for running sinopia

### ISSUE THREAD

**Issue by kbdaitch** [rlidwka/sinopia#226]
I am running sinopia v1.0.1 inside a docker container. Every few days, the OOM killer decides to kill my docker container.

I get something like this on `dmesg`:
```bash
[4378071.058541] Out of memory: Kill process 30014 (sinopia) score 590 or sacrifice child
[4378071.058613] Killed process 30014 (sinopia) total-vm:1157812kB, anon-rss:295172kB, file-rss:0kB
```

Are there any suggested memory requirements? My cloud VM hasn't got much free (like 58M).

**Comment by rlidwka** [comment]
Most node.js/io.js applications I saw use at least 80M. Looking at my production setup, sinopia uses 110M right now. So say 150M limit should be enough I hope.

Are you using `npm search`? Because that's the only part I know of that uses really huge amount of memory.

**Comment by kbdaitch** [comment]
Thanks for the prompt reply. No I am not using `npm search` but that is good to know.

I just bumped up my specs on the cloud VM. Thanks for bringing `npm` (without the DB) to us. :+1:
