### ISSUE TITLE
How does Sinopia find newer Packages?

### ISSUE THREAD

**Issue by Z3roCoder** [rlidwka/sinopia#228]
Lets say, package "xxx" with version "1.2.0" is currently on Sinopia, but it has gotten that package from npmjs.org because the package was not on Sinopia before.

Now, lets say that npmjs now has a newer package with the version "2.0.0".

When I now call "npm install xxx", Sinopia will use the package on the server, right? How can I update the package on the Server to 2.0.0 without much effort? By simply deleting the package? Or like, calling npm update?

**Comment by rlidwka** [comment]
Basically, every time you run "npm install xxx", sinopia will check if there is a newer version available on npm.

So you don't have to update anything, it'll be done automatically.

**Comment by Dev661** [comment]
@rlidwka 
Sorry could you please elaborate this: "Basically, every time you run "npm install xxx", sinopia will check if there is a newer version available on npm." Does it mean npmjs overwrites our private changes if there is any new update from npmjs while working on private NPM?

**Comment by rbecheras** [comment]
Yes, npm select the latest version. If you dont want this behavior, you can block the version in dependencies (package.json), or register your own uppper version in sinopia, with a prerelease suffix, for example  v1.1.0-sinopia.1

This way, the "override" will happend only when the upstream repo reach v1.1.0

**Comment by rlidwka** [comment]
> Does it mean npmjs overwrites our private changes if there is any new update from npmjs while working on private NPM?

If you are working on private npm packages, you would usually want to turn this off for those packages (see below).

But yes it can do this, and it depends on the configuration of a particular package. Here is an example:

```yaml
packages:
  'foo*':
    access: user
    publish: user
    proxy: npmjs # <-- this
```

It means that there are two sources where packages can come from:
  - `user` can publish it (`publish` key)
  - it can be retrieved from `npmjs.org` (`proxy` key)

If user publishes `foobar@1.2.3`, it will never be overwritten. However, if `npmjs.org` has `foobar@1.2.4`, you'll have both and npm will install second one by default.

So if you want to turn this off, remove or comment out "proxy" line.

Please check fully commented config file example [here](https://github.com/rlidwka/sinopia/blob/6b3617754c7bac6ad08366046be87361bb8a6b24/conf/full.yaml#L54-L74).
