### ISSUE TITLE
Run "npm adduser" silent?

### ISSUE THREAD

**Issue by Z3roCoder** [rlidwka/sinopia#230]
Hello. I currently have a huge problem
I have an automatic publishing-process for my npm packages. Now I have one problem - On every build, a new version of npm gets installed.

Before I can publish something, I have always to use "npm adduser" - Can I somehow pass the username, pass and email as parameters? Because my build-script cannot pass values for those prompts or can it?

**Comment by rlidwka** [comment]
If `~/.npmrc` is not removed, you don't have any problem. npm will load auth data from there even if it gets reinstalled.

If you have a new environment each time (e.g. CI), you can run:

```
npm set //localhost:4873/:_authToken 'm/32No+rQwBgeYPm6MAQ0g=='
```

Where `localhost:4873` is the registry address and that weird thing (`m/32...` in this example) is the auth token (look into `~/.npmrc` after `adduser` and copy-paste it).

Also, you might want to ask this question here:
https://github.com/npm/npm

**Comment by Z3roCoder** [comment]
This does not work for me. I always receive

npm ERR! need auth auth and email required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

**Comment by rlidwka** [comment]
Well, I could take a look if you show full npm logs you're receiving.

// ref https://github.com/npm/npm/issues/7910
