### ISSUE TITLE
Wrong web UI logo

### ISSUE THREAD

**Issue by dsuckau** [rlidwka/sinopia#234]
Just a little thing:

after updating to 1.2.1 (from 1.0.0 I think) I recognized, that the npm logo in the web UI is wrong now. I see just the upper left corner of the logo, because it is too big now.

I think it belongs to https://github.com/rlidwka/sinopia/commit/d7c95d6cd6a62c16aa8c93ea1681dca32111c481

"/-/logo-sm" has changed to "../../-/logo"

When I change it via Firebug to "../../-/logo-sm", everything looks good again.

**Comment by rlidwka** [comment]
I removed `/-/logo-sm` endpoint completely, it's only `/-/logo` now.

See https://github.com/rlidwka/sinopia/commit/d7c95d6cd6a62c16aa8c93ea1681dca32111c481#diff-cf1aee04ff5a4d8f39e94ead2aea5451L74

I'm not sure why you see the old one. Maybe try clearing browser cache/press ctrl+f5/etc.?

**Comment by dsuckau** [comment]
You're so right, sorry. I was sure that it was the first thing I tried to clear the cache. But it was really just the cache now... Thank you.
