### ISSUE TITLE
solution to prevent accidental publishing to external registry

### ISSUE THREAD

**Issue by iamstarkov** [rlidwka/sinopia#240]
Is there any solution to prevent accidental publishing to external registry? Since Sinopia is good on proxying, then we don’t need external registry for access packages. Since we have a reason to have Sinopia as a internal registry for private and _simple_ hosting our packages, then we don’t want to accidentally publish them to external registry. Is there any solution?

"accidentally" means if newly hired programmer will not logged in into internal Sinopia and will have access to the package and will run `npm publish` — shit will happen. Also experienced user also can accidentally publish packages into external registry if smth bad will happen with their `~/.npmrc` files

**Comment by JSteunou** [comment]
https://docs.npmjs.com/misc/registry#i-don-t-want-my-package-published-in-the-official-registry-it-s-private

**Comment by iamstarkov** [comment]
works perfectly, thanks!
