### ISSUE TITLE
User not being authorized on some requests

### ISSUE THREAD

**Issue by stevie-mayhew** [rlidwka/sinopia#243]
It seems like the authorization for my user isn't being sent with every request, or something weird is going on somewhere in NPM.

Any help with this would be appreciated!

`.npmrc` in base folder:

```
registry = <url>:4873
always_auth = true
//<url>:4873/:_authToken=<token>
```

Sinopia log:
```
 http  <-- 304, user: stevie, req: 'GET /vinyl-buffer', bytes: 0/0
 http  <-- 403, user: undefined, req: 'GET /desandro-classie/-/desandro-classie-1.0.1.tgz', error: unregistered users are not allowed to access package desandro-classie
 http  <-- 403, user: undefined, req: 'GET /form-serialize/-/form-serialize-0.6.0.tgz', error: unregistered users are not allowed to access package form-serialize
 http  <-- 403, user: undefined, req: 'GET /spin.js/-/spin.js-2.1.0.tgz', error: unregistered users are not allowed to access package spin.js
 http  --> 304, req: 'GET https://registry.npmjs.org/babel', bytes: 0/0
 http  <-- 200, user: stevie, req: 'GET /babel', bytes: 0/8229
 http  <-- 403, user: undefined, req: 'GET /vinyl-buffer/-/vinyl-buffer-1.0.0.tgz', error: unregistered users are not allowed to access package vinyl-buffer
 http  --> 304, req: 'GET https://registry.npmjs.org/babelify', bytes: 0/0
 http  <-- 200, user: stevie, req: 'GET /babelify', bytes: 0/2611
 http  <-- 403, user: undefined, req: 'GET /babel/-/babel-5.1.13.tgz', error: unregistered users are not allowed to access package babel
 http  <-- 403, user: undefined, req: 'GET /babelify/-/babelify-6.0.2.tgz', error: unregistered users are not allowed to access package babelify
```

**Comment by Levino** [comment]
I have similar issues

**Comment by rlidwka** [comment]
I can't reproduce it. Which npm version and which sinopia version are you using?

**Comment by stevie-mayhew** [comment]
```{ http_parser: '1.0',
  node: '0.10.38',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.36',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1m',
  npm: '1.4.28' }```

Sinopia 1.2.2

**Comment by grimborg** [comment]
Same here. Using latest version of sinopia. I'm logged in (and I was able to unpublish my own package), but I can't publish it or install anything.

Config snippet:

        packages:
          '@*/*':
            # scoped packages
            access: $authenticated
            publish: $authenticated

          '*':
            # you can specify usernames/groupnames (depending on your auth plugin)
            # and three keywords: "$all", "$anonymous", "$authenticated"
            access: $authenticated

            # allow all known users to publish packages
            # (anyone can register by default, remember?)
            publish: $authenticated

            # if package is not available locally, proxy requests to 'npmjs' registry
            proxy: npmjs

**Comment by grimborg** [comment]
Check that you have `always-auth=true` on your `.npmrc`. That fixed it for me.

**Comment by Levino** [comment]
Maybe it is just a typo above?

> always_auth = true

instead of 

> always-auth = true

as @grimborg noted.

If that is the reason, this issue should be closed.

**Comment by stevie-mayhew** [comment]
Thats it! Thanks @grimborg and @Levino 

Some of the NPM configuration parameters are wee gotchas waiting to happen :\
