### ISSUE TITLE
How to run sinopia as a background process on Mac OS?

### ISSUE THREAD

**Issue by kostrse** [rlidwka/sinopia#252]
The question may seem stupid, anyway:
What is the recommended approach of configuring sinopia to run as a daemon process on Mac OS? Would be great to have control commands like start/stop/restart available...

Would be great to have this added to Wiki / frontpage README file.

Thanks!

**Comment by rlidwka** [comment]
You can use any supervisor (for example, [PM2](https://github.com/Unitech/PM2) or [forever](https://github.com/foreverjs/forever)) to deamonize it. Those programs will also provide start/stop/restart commands.

It is documented in https://github.com/rlidwka/sinopia/blob/master/SERVER.md , mostly for linux, but macos should work similarly.

**Comment by kostrse** [comment]
Thank you, didn't notice that page :)

**Comment by justinmchase** [comment]
`forever` works well. This issue can probably be closed.
