### ISSUE TITLE
npm not getting latest version with "^version"

### ISSUE THREAD

**Issue by klinquist** [rlidwka/sinopia#259]
In my private repo, I have 0.1, 0.2, & 0.3 of privatePackage.

In my packages.json of a node script I have a dependency of privatePackage: "^0.1"

during npm install, npm is pulling down 0.1 instead of 0.3.

**Comment by BDiehr** [comment]
Check out here for what a caret range is: https://docs.npmjs.com/misc/semver#caret-ranges-1-2-3-0-2-5-0-0-4

Long story short, ^ will allow npm to pull the most up to date package that does not increment the left most digit. In your case, the left most is the 1.

**Comment by klinquist** [comment]
I'm actually using the following versions:

0.0.91
0.0.92
0.0.93


^0.0.91  is still pulling 0.0.91 ... is that correct?

**Comment by BDiehr** [comment]
from the docs: ```^0.0.3 := >=0.0.3 <0.0.4```
I'm going to guess what is happening is the following:
```^0.0.91:= >=0.0.91 <0.0.92```

**Comment by klinquist** [comment]
Got it. Thank you for your help.
