### ISSUE TITLE
Sinopia appears to not support requests by version range

### ISSUE THREAD

**Issue by justinmchase** [rlidwka/sinopia#260]
For example:
`https://myregistry.com/angular/^1.4.0`

But these queries do work:
`https://registry.npmjs.org/angular/^1.4.0` 
`https://myregistry.com/angular/1.4.0`

So for some reason sinopia appears to be dropping the valid semver range characters from the request.

**Comment by justinmchase** [comment]
The bug appears to be in `index-api.js, line 58`

```
var t = Utils.get_version(info, version)
```

Where the version parameter should actually be a (`range`)[https://www.npmjs.com/package/semver#ranges] instead of a (`version`)[https://www.npmjs.com/package/semver#versions].

I'm looking at the code now, will try to submit a pull request but it is pretty new to me still.

**Comment by justinmchase** [comment]
Pull request for this issue: https://github.com/rlidwka/sinopia/pull/261

**Comment by rlidwka** [comment]
Why should it be a range instead of a version? 

What software uses those requests with semver ranges to the registry? I just checked, latest npm doesn't do it.

**Comment by justinmchase** [comment]
Well I was using it to search for the right version based on whats in the package.json file. npmjs.org supports it so I assumed the lack of it in sinopia was an oversight. What do you mean by npm doesn't do it?

**Comment by justinmchase** [comment]
I think I understand what you're saying. The npm _client_ doesn't actually call the server with this url at all. The server seems to support it but it may be obsolete or just undocumented. I found that I can just query the root package, which gets me all versions and then I can use semver to get the same information so I believe that I can work with this not being supported in sinopia.

**Comment by justinmchase** [comment]
This isn't actually necessary, thanks for explaining.
