### ISSUE TITLE
Handling User Password Changes

### ISSUE THREAD

**Issue by geekytime** [rlidwka/sinopia#262]
We're using sinopia-ldap, and it is awesome. Until someone changes their ldap password. Then it seems like our only option is to manually delete the user from the sinopia database, is that right?

It'd be nice if the user could just remove the token from their `.npmrc` file and re-add themselves. That would potentially mean adding a bit more handling [here](https://github.com/rlidwka/sinopia/blob/master/lib/auth.js#L49).

Since the user is properly authenticated through ldap in our case, the Sinopia user is kind of a pass-through, so we don't care if they can readd themselves, but I'm guessing this would cause problems for the other auth handlers, making it too easy to hijack accounts. This would lead us to a full-on password reset form with email verification, but that seems a little bit heavy-handed.

Should we just stop whining and make the admins remove the users by hand, or is there another acceptable way we could allow for ldap password resets?

**Comment by rlidwka** [comment]
> Then it seems like our only option is to manually delete the user from the sinopia database, is that right?

There is no such thing as sinopia database. At least, passwords aren't stored anywhere.

Token you see in `.npmrc` is actually an encrypted password. If you change password, remove token from `.npmrc` and run `npm adduser` again.

Maybe you're using both `htpasswd` and `ldap` plugins, and users are checked against both for some reason? Can you show your config file?

**Comment by geekytime** [comment]
You know what, I may have trusted our user's story a little bit too much. I will circle back and do some more in-depth testing with them to make sure they can log in properly.
