### ISSUE TITLE
Intermittent missing directory in published module

### ISSUE THREAD

**Issue by jimsheldon** [rlidwka/sinopia#264]
We are running version 1.3.1.  We have a module that we publish to sinopia, where a directory named 'models' at the root level intermittently goes missing.

Publishing a new version of the module fixes the problem most of the time.

Is this a known issue by chance?  How could I provide additional debugging information?

Thank you!

**Comment by rlidwka** [comment]
You can check sinopia storage directory, find the tarball and manually check what is inside.

Or even better, run `npm pack` and check if that folder is packed into the tarball.

Sinopia never unpacks any tarballs, so I really doubt it is an issue with sinopia. Maybe race condition in npm again.

**Comment by jimsheldon** [comment]
Thanks for the reply.  I verified that it was missing from the tarballs from sinopia's storage area as well.

It wouldn't surprise me at all that it is an issue with npm.  I like the `npm pack` suggestion, I will add that to the module's build steps, then if it reoccurs I will have something to examine.

I'll close this out, thanks again!
