### ISSUE TITLE
README.md of package is not parsed entirely

### ISSUE THREAD

**Issue by SamVerschueren** [rlidwka/sinopia#270]
If the README.md of the package has a `JavaScript` block for instance, it will result in an empty `<pre>` tag in the web interface.

```
    ```JavaScript
    // My javascript code
    ```
```

Results in 

```
```

**Comment by rlidwka** [comment]
This was a bug in [render-readme](https://github.com/rlidwka/render-readme).

Fixed, thanks for reporting!
