### ISSUE TITLE
Sinopia HTML broken when hosted behind SSL proxy

### ISSUE THREAD

**Issue by tkambler** [rlidwka/sinopia#273]
My Sinopia server uses the default port of 4873. Incoming traffic is first routed through a proxy server (https, port 443) then proxied to Sinopia on port 4873. Sinopia's templates are setup such that they reference their assets using absolute URLs that use the port defined in the configuration file. This shouldn't be necessary, and it causes the page to break - Chrome refuses to load insecure assets over port 4873 in this instance.

**Comment by tellnes** [comment]
There is a config option named `url_prefix`.

https://github.com/rlidwka/sinopia/blob/v1.4.0/conf/full.yaml#L80-L81

**Comment by rlidwka** [comment]
> This shouldn't be necessary, and it causes the page to break

What headers does your https proxy send? How should sinopia respond in this case?

You can use `url_prefix` as mentioned above, but I think it makes sense to have a more useful default there if possible.

**Comment by tkambler** [comment]
I was unaware of the `url_prefix` config option. That should resolve my issue.
