### ISSUE TITLE
Rename history.md to CHANGELOG.md

### ISSUE THREAD

**Issue by Alexandre-io** [rlidwka/sinopia#276]
Hey, first of all thank you so much for this package!

Is it possible to rename the current changlog file to CHANGELOG.md instead of History.md ?

Thanks!

**Comment by rlidwka** [comment]
`History.md` contains the most important changes, `Changelog.md` usually contains every single change.

There is a difference, and imho `History.md` makes more sense here, since we don't list everything (as opposed to `ChangeLog.md` of `io.js` which lists every commit).
