### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by ElQuesodoro** [rlidwka/sinopia#283]
First off, thank you for writing and supporting this!

I'm curious how sinopia supports each package's dependencies.  Say you have package foo 1.2.3 that has in it's package.json a requirement for bar '~2.3.4'.  When you initially pull down foo into your sinopia storage it brings in bar at 2.3.4.  A few days after this, bar gets upgraded on npmjs.org to 2.3.5.  If you never request foo at any version other than 1.2.3, will it check if bar has been upgraded?

We're trying to avoid dependency's dependencies upgrading without us knowing about it.

**Comment by rlidwka** [comment]
> If you never request foo at any version other than 1.2.3, will it check if bar has been upgraded?

Sinopia doesn't manage dependencies, npm does.

That's what will happen:

1. `foo@1.2.3` and `bar@2.3.4` are published
2. npm requests `foo@latest`, sinopia downloads data for all `foo` versions, npm picks `foo@1.2.3` (only choice)
3. npm requests `bar@~2.3.4`, sinopia downloads data for all `bar` versions, npm picks `bar@2.3.4` (only choice)
4. `foo@1.2.3`, `bar@2.3.4`, `bar@2.3.5` are published
5. npm requests `foo@latest`, sinopia downloads data for all `foo` versions, npm picks `foo@1.2.3` (only choice)
6. npm requests `bar@~2.3.4`, sinopia downloads data for all `bar` versions, npm picks `bar@2.3.5` (out of the two npm makes the choice)

So yes, `bar` will be upgraded.

> We're trying to avoid dependency's dependencies upgrading without us knowing about it.

The best way to ensure this is to use `npm shrinkwrap`.

This is what this package itself does for managing its dependencies, see [here](https://github.com/rlidwka/sinopia/blob/master/npm-shrinkwrap.json). If you have this file in, no other versions will be installed no matter what `package.json` says.

**Comment by ElQuesodoro** [comment]
Thank you for the reply!
