### ISSUE TITLE
One of the uplinks is down, refuse to publish

### ISSUE THREAD

**Issue by alallier** [rlidwka/sinopia#289]
Issue #124 talks about the system clock being off by a year, that is not the case for me

**Comment by alallier** [comment]
Seemed to get Sinopia working after all. Closing this issue.

**Comment by francoislg** [comment]
Care to explain what was done to fix it ?
I'm having the same problem.

Managed to add one package, closed command line, and when I re-opened it, I started getting this error.

**Comment by alallier** [comment]
That's exactly what happened to me. I didn't do anything specific to fix it.

**Comment by francoislg** [comment]
Noticed this when I tried to do "npm install" in a project, I didn't do the "npm set ca null" command, and my sinopia could access the https url for the real npm repository. 

So I'm thinking that *might* be the cause for the first error.

**Comment by alallier** [comment]
Can you provide a bit more details on how you replicate this issue. I'm trying to see if I can replicate it. Did you already have the package published when you did an `npm install`?

**Comment by francoislg** [comment]
I had one local package published, but I tried to "npm install" on another public package from npm, which got me "npmjs.com is unavailable" or something like that.

Then I ran "npm set ca null", my "npm install" worked. I didn't get the "One of the uplinks is down, refuse to publish" on a publish for a local package since then.

Might be a coincidence thought.

**Comment by alallier** [comment]
Did you run this command at setup `npm set registry http://localhost:4873/`?

**Comment by francoislg** [comment]
Yes I did. And restarted cmd line right after it, just in case.

**Comment by alallier** [comment]
Don't run that command. That command sets npm to always globally refer to the local registry. So if your sinopia server is down and you try to pull a public package it will fail because the registry is set to a local registry not running. Instead don't run this command, since npm added a nice option to specify registries in the command line when needed. 

For example

If you want a local package to be pushed to your local registry add this to your package.json
```
"publishConfig": {
"registry": "http://localhost:4873/"
}
```

Make sure `"private": true` doesn't exist

Then when you publish this package it always guaranteed to publish to the registry configured in package.json.

Then when you install the package you specify `npm install packageName --reg http://localhost:4873/`. Pulling the package from your local registry.

So now you can still pull any global package from npm with just a normal `npm install packageName`.
Eliminating the need to globally configure npm with a registry which always looks to the local registry (which could fail for many reasons)

I have been meaning to open a PR with an updated README for this project. That will come soon.

Let me know if any of this confuses you  and I can explain better/further.

**Comment by francoislg** [comment]
That is pretty nice, I had no idea :+1:

**Comment by francoislg** [comment]
Thinking about it, I think the reason you set "npm set registry http://localhost:4873/" is for use case 2, "Cache npmjs.org registry."

I agree that explicitly specifying localhost for local package is useful, but when calling npm install without sinopia being set as the default registry kind of renders it's cache useless.

Either way, I stopped having this problem. If it ever comes back, I'll reply here with an update :)

**Comment by alallier** [comment]
You are right totally forgot about use case 2, I guess you pick which way as you need and want

**Comment by macdosi** [comment]
what about using scopes ?
