### ISSUE TITLE
What Database is used?

### ISSUE THREAD

**Issue by Dev661** [rlidwka/sinopia#295]
Hi there,

Documentation says "Sinopia keeps its own small database"; so what database is being used?

On the other hand it is mentioned "If you want to use a database instead, ask for it, we'll come up with some kind of a plugin system." So is any database being used or not? If no Is there any chance to get the version which works with DB? It seems right now all info is being save din config.yaml as opposed to a DB, am I right?

I appreciate your help in this matter :-)

**Comment by yzach** [comment]
It uses no DB at all. Quoting documentation

> This application is supposed to work with zero configuration, so filesystem is used as a storage.

**Comment by rbecheras** [comment]
@rlidwka , this issue should be closed

**Comment by rlidwka** [comment]
> Documentation says "Sinopia keeps its own small database"

I was meaning "a bunch of files in JSON format". Not sure whether it can be called a database or not. Sorry for the confusion.
