### ISSUE TITLE
core-util-is unlink error

### ISSUE THREAD

**Issue by justinmchase** [rlidwka/sinopia#299]
Because it asked me to report it I'm getting this when running on windows:

```
 fatal --- uncaught exception, please report this
Error: ENOENT: no such file or directory, unlink 'c:\Users\justin\.config\sinopia\storage\core-util-is\package.json.tmp8789713180158287'
    at Error (native)
```

earlier:
```
http --> 200, req: 'GET https://registry.npmjs.org/core-util-is', bytes: 0/2559
http  <-- 200, user: undefined, req: 'GET /core-util-is/1.0.1', bytes: 0/508
http  <-- 200, user: undefined, req: 'GET /core-util-is', bytes: 0/668
http  --> 200, req: 'GET https://registry.npmjs.org/core-util-is', bytes: 0/2559
http  <-- 200, user: undefined, req: 'GET /core-util-is', bytes: 0/666
http  <-- 200, user: undefined, req: 'GET /core-util-is', bytes: 0/666
```

Mixed in with a lot of other requests but that's the only core-util-is related entries. I restarted the server and tried again and it worked fine after that.

**Comment by rlidwka** [comment]
Okay, thanks. Are you seeing it for the first time, or does it happen often?

If you have a way of reproducing it reliably, please let us know.

**Comment by justinmchase** [comment]
My production server is actually ubuntu and we are not seeing the error there. I was running it locally for some testing, once it's cached a bunch of stuff it seems to go away. But if I wipe out the cache and try again these do popup.
