### ISSUE TITLE
Error when publishing a scoped package with 1.4.0

### ISSUE THREAD

**Issue by mrapczynski** [rlidwka/sinopia#307]
Working with Sinopia. Trying to publish a scoped package for the first time, and I am getting errors. Even tried to publish a non-scoped package, and still get the errors My config is almost the default so it should not be complicated.

Sinopia logs the following:

```
 info  <-- 153.18.100.233 requested 'PUT /@fhda%2ffhda-logging-splunk'
 error --- unexpected error: EBADF, Bad file descriptor
Error: EBADF, Bad file descriptor
    at Error (native)
 http  <-- 500, user: ets, req: 'PUT /@fhda%2ffhda-logging-splunk', error: internal server error
 info  <-- 153.18.100.233 requested 'PUT /@fhda%2ffhda-logging-splunk'
 http  <-- 409, user: ets, req: 'PUT /@fhda%2ffhda-logging-splunk', error: this tarball is already present
 info  <-- 153.18.100.233 requested 'GET /@fhda%2ffhda-logging-splunk?write=true'
 http  <-- 200, user: ets, req: 'GET /@fhda%2ffhda-logging-splunk?write=true', bytes: 0/266
```

And NPM on my Mac dumps this:

```
mrapczynski @ ~/Development/Node/Packages/FHDA Splunk Logging $ npm publish
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "publish"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2

npm ERR! Unexpected token u
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mrapczynski/Development/Node/Packages/FHDA Splunk Logging/npm-debug.log
```

Since this is happening out of the box, did I configure something wrong. Also I have Sinopia running in a Docker container, but there were no errors reported on install so not sure what's up.

**Comment by mrapczynski** [comment]
Here is a screenshot of the UI showing some weird name issues after publishing. Nothing shows up in the list unless I type something into the search box.

<img width="1220" alt="screen shot 2015-09-23 at 4 38 51 pm" src="https://cloud.githubusercontent.com/assets/258614/10061865/aa7f5a58-6211-11e5-8544-264ea88a4d99.png">

**Comment by rlidwka** [comment]
Can you remove sinopia storage folder and try again? That's usually `~/.local/share/sinopia/storage/`, not sure where is it in the docker.

I see this EBADF error for the first time here, so I would assume it's a temporary thing.

**Comment by fernandoneto** [comment]
im getting the same error. im ruuning sinopia inside a docker container too. 
@mrapczynski did you solve your problem?

**Comment by mrapczynski** [comment]
@fernandoneto I ended up using my existing Nexus repository (it does Maven, NPM, etc) and setting up my dev environment to proxy through it. I was trying to avoid a proxied repo but in reality it seems perfectly fine. Once in a rare while I run into an application that is very Docker resistant and not necessarily a bug.

**Comment by fernandoneto** [comment]
I change my default `storage` path and work just fine.
im using a docker container that i made with a docker-nfs-server.

https://github.com/cusspvz/btsync.docker
https://github.com/fernandoneto/docker-sinopia

**Comment by fernandoneto** [comment]
@mrapczynski for me the problem as been fixed changing the version of node. 
i was using `0.12.7` and update to `4.1.2`
