### ISSUE TITLE
 tunneling socket could not be established

### ISSUE THREAD

**Issue by andytorres** [rlidwka/sinopia#315]
Hi everyone:
I've been looking for something like sinopia for a while, so I got it up and running in my work server. The server has internet access through a proxy, so I edited config.yaml and set `http_proxy: http://192.168.66.66:3128`. 
The thing is, in my local PC, I set `npm config set registry "http://npm.mycompany.com:4873"`, but when I write, for example, `npm install -g cordova -dd`, the server console shows me this:
    info  <-- 10.17.0.25 requested 'GET /cordova'
    info  --> making request: 'GET https://registry.npmjs.org/cordova'
    http  --> ERR, req: 'GET https://registry.npmjs.org/cordova', error: tunneling socket could not be established, cause=140050610448192:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795:
I suppose it's a proxy problem, can someone throw some light about this?
Thanks in advance

**Comment by andytorres** [comment]
Looks like setting `export http_proxy` and `export https_proxy` in my local environment did the trick... however, I'd like yo know if the same result can be achieved through sinopia config.yaml.
With regards, Andy

**Comment by micheledisalvatore** [comment]
Hi @andytorres I have the same problem, can you explain me better how did you solve it?

Thanks

**Comment by micheledisalvatore** [comment]
Solved. It needs only the proxy settings in the config.yaml
