### ISSUE TITLE
copy packages to storage folder

### ISSUE THREAD

**Issue by andytorres** [rlidwka/sinopia#316]
I have a .npm folder in my /home which contains all the npm packages I've ever needed. But now, I set up a sinopia server in my development server, so I would like to copy all these packages I have in my local PC to the server, so it doesn't need to download them later is someone else needs them. I tried to copy the contens of my .npm folder to sinopia's storage folder, but it hasn't worked for me. 
Am I doing the procedure the wrong way? Is there a way to do what I want, or the server has to download the packages anyway?
Thanks in advance,
Andy

**Comment by Asgator** [comment]
@andytorres have you done it?
