### ISSUE TITLE
uplinks and authentication

### ISSUE THREAD

**Issue by deployable** [rlidwka/sinopia#322]
I use an npm registry that requires `_auth` to be set in `.npmrc`

```
_auth="base64encoded_user:password"
```

It it possible to configure this for a Sinopia `uplinks` entry in `config.yaml`?

**Comment by ghost** [comment]
You might want to check out https://github.com/rlidwka/sinopia/pull/269. The fix works in case you need this before the pull request gets merged.

**Comment by deployable** [comment]
Thanks! I missed that one.
