### ISSUE TITLE
Revoking auth tokens

### ISSUE THREAD

**Issue by sebastiandedeyne** [rlidwka/sinopia#338]
Where are the auth tokens stored on the server? Would like to revoke one of mine, but can't find anything besides what's stored in `htpasswd`.

**Comment by ChadKillingsworth** [comment]
They aren't stored on the server. The auth "tokens" are simply the username/password combination encrypted. Therefore, they cannot be revoked - the user has to change their underlying password.

**Comment by sebastiandedeyne** [comment]
Got it, thanks!
