### ISSUE TITLE
'npm install' fails when registry.npmjs.org is unreachable

### ISSUE THREAD

**Issue by chazzlabs** [rlidwka/sinopia#37]
I found sinopia while researching the best way to mirror the npm registry, and I'm running into an issue that may stem from my misunderstanding of npm.  Please forgive me if there's a more appropriate place for this.

I've got sinopia up and running perfectly on an Ubuntu VM, and I can successfully download the modules defined in my project's package.json.  However, I noticed that there are still some GET requests that are hitting registry.npmjs.org.  I looked into some of the package.json files used by plugins in my node_modules directory, and I noticed lines like this:

``` javascript
  "_from": "https://registry.npmjs.org/grunt-contrib-uglify/-/grunt-contrib-uglify-0.2.0.tgz",
  "_resolved": "https://registry.npmjs.org/grunt-contrib-uglify/-/grunt-contrib-uglify-0.2.0.tgz"
```

These match the URLs being hit when I run 'npm install'.  There are several more.

I experimented with what would happen if I made registry.npmjs.org unreachable (by turning off my network card).  My next 'npm install' failed with "fetch failed" errors on each of the registry.npmjs.org URLs.  

Any suggestions would be much appreciated.

Edit:

It looks like I neglected to consider what effect the presence of an npm-shrinkwrap.json file would have.  After removing the file, my issue looks resolved.

**Comment by jovylle** [comment]
I do have this error currently.
