### ISSUE TITLE
npm owner always returns admin party!

### ISSUE THREAD

**Issue by doug-wade** [rlidwka/sinopia#386]
We're using sinopia at Redfin, and very happy with it.  However, we want to use it to help decouple teams from each other, and a big part of that is ascribing ownership, which npm supports with `npm owner ls`.  Unfortunately, it seems to [point at a field called "maintainers"](https://github.com/npm/npm/blob/master/lib/owner.js#L119) that the npm _repository_ magically adds at publish time, and not something added by the cli.  I've tried: 
    1.) adding an author field to package.json 
    2.) adding a contributors field to package.json 
    3.) adding a maintainers field to package.json
    4.) npm owner add doug.wade @redfin/nlp

That last one throws this error

```
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "owner" "add" "doug.wade" "@redfin/nlp"
npm ERR! node v4.3.1
npm ERR! npm  v3.8.2

npm ERR! Cannot read property 'length' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/code/npm/npm-debug.log
```

which has this stack trace

```
40 verbose stack TypeError: Cannot read property 'length' of undefined
40 verbose stack     at /Users/doug.wade/code/npm/lib/owner.js:230:46
40 verbose stack     at saved (/Users/doug.wade/code/npm/lib/cache/caching-client.js:168:7)
40 verbose stack     at /Users/doug.wade/code/npm/node_modules/graceful-fs/polyfills.js:210:7
40 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
```

It's a little surprising, since npm seems [to have logic for dealing with an empty owner hash](https://github.com/npm/npm/blob/master/lib/owner.js#L145), but it'd be nice to get the magical maintainer hash with the author assigned out of the box with sinopia.

There may also be a workaround using package.json, but I seem to have hacked package.json to decieve `npm show` just fine

```
dougwade code/npm ‹master› » npm show generator-koa-angular maintainers
[ 'douglas.wade <douglas.b.wade@gmail.com>' ]
dougwade code/npm ‹master› » npm show @redfin/nlp maintainers
[ 'Doug Wade <doug.wade@redfin.com>' ]
```

**Comment by doug-wade** [comment]
Trying to patch npm to fix this -- when you get past the "cannot read property 'length' of undefined" error, npm throws an error that really seems to indicate we'll need to implement some incoming transform

```
53 verbose stack Error: bad incoming package data : @redfin/nlp
53 verbose stack     at makeError (/Users/doug.wade/code/npm/node_modules/npm-registry-client/lib/request.js:264:12)
53 verbose stack     at CachingRegistryClient.<anonymous> (/Users/doug.wade/code/npm/node_modules/npm-registry-client/lib/request.js:252:14)
53 verbose stack     at Request._callback (/Users/doug.wade/code/npm/node_modules/npm-registry-client/lib/request.js:172:14)
53 verbose stack     at Request.self.callback (/Users/doug.wade/code/npm/node_modules/request/request.js:199:22)
53 verbose stack     at emitTwo (events.js:87:13)
53 verbose stack     at Request.emit (events.js:172:7)
53 verbose stack     at Request.<anonymous> (/Users/doug.wade/code/npm/node_modules/request/request.js:1036:10)
53 verbose stack     at emitOne (events.js:82:20)
53 verbose stack     at Request.emit (events.js:169:7)
53 verbose stack     at IncomingMessage.<anonymous> (/Users/doug.wade/code/npm/node_modules/request/request.js:963:12)
```

**Comment by doug-wade** [comment]
npm actually documents this transform on publish [here](https://docs.npmjs.com/files/package.json#people-fields-author-contributors)

**Comment by Robinfr** [comment]
Would be nice to get an update on this.

**Comment by doug-wade** [comment]
@Robinfr you should check out https://github.com/verdaccio/verdaccio ; this project seems abandoned.

**Comment by Robinfr** [comment]
@doug-wade thanks, I'll check it out.
