### ISSUE TITLE
Does sinopia have feature to cache public git repositories?

### ISSUE THREAD

**Issue by sharikovvladislav** [rlidwka/sinopia#413]
Hi,

Thank you for your great product.

Does sinopia have feature to cache public git repositories? So public repository will be clonned to the Sinopia server (host filesystem) and when somebody use `npm install`, npm will get package from local git server, not from github/bitbucket.

It will be usefull to save time for accessing github/bitbucket. If data will be in the LAN, npm install will work significaly fast.

So does sinopia have this feature? For example, [private-bower](https://www.npmjs.com/package/private-bower) (have same feature for bower registry, like sinopia have for npm registry).

**Comment by shinxi** [comment]
Not sure, but it looks like sinopia doesn't cache the public packages.

**Comment by sharikovvladislav** [comment]
So, sinopia doesn't cache git repositories to get faster access to public packages then (like private-bower) and, also, it doesn't cache any packages (not git, only packages) on the server (where sinopia is installed). Am I right?
