### ISSUE TITLE
How to migrate sinopia to another host?

### ISSUE THREAD

**Issue by sharikovvladislav** [rlidwka/sinopia#419]
Hi, 

Thank you for great product.

Imagine, I have `sinopia` and it worked for 1 month. People added some npm modules in it. Now I want to move sinopia to other host.

How I can move `sinopia` so already registered packages wouldn't be lost?

**Comment by gaelreyrol** [comment]
Hi,

Did you installed it via Docker ?

**Comment by sharikovvladislav** [comment]
No. I did it not through docker. I used npm and installed it globally.

What if I installed it via Docker?

**Comment by Robinfr** [comment]
You can just move the entire sinopia folder to the new machine.
