### ISSUE TITLE
use public namespaced packages

### ISSUE THREAD

**Issue by gabwh** [rlidwka/sinopia#421]
Hi, 
my project is using some public npm packages which depend on public namespaced pakages. E.g. `protractor` is depending on `@types/node` and `@types/jasmine`.
Now, my configuration file looks like this:
packages:

```
  '@acme/*':
    access: $authenticated
    publish: admin
    storage: ./wh-storage

'@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs

'*':
    access: $all
    publish: $authenticated
    proxy: npmjs
```

If I try to install any of my private packages all is fine e.g. `@acme/mypack`, however, if I try to install `@types/node` I get this error:
`no such package available : @types/node`

Any suggestion on how to configure sinopia tu support public namespaced packages?

Thanks

**Comment by redboul** [comment]
Hi, 

The lastest tag does not contains the fixes to support correctly packages starting with `@` (they are replaced with `%40` on remote registry retrieval).

However, the fix is in the master, so updating the [`lib/up-storage.js`](https://github.com/rlidwka/sinopia/blob/master/lib/up-storage.js) file locally should resolve your issue.

BR

**Comment by gabwh** [comment]
Hi @redboul,
Thanks for the response. In the meantime I had implemented a fix similar to the one you did. It's working but your solution looks more elegant. I'll update and give a try.

Thanks,
Gab

**Comment by dnascimento** [comment]
Can we have a release with this fix? Angular2 uses namespaces :/

**Comment by ghost** [comment]
You can override the registry for specific scopes, if that's the easiest workaround. For example:

```
npm config set @types:registry https://registry.npmjs.org/
```

That would tell `npm` to always get anything for the `@types` scope directly from the official server on the internet, bypassing Sinopia entirely. Obviously it won't be the right fix for everyone. `npm` would need internet access (via a proxy if necessary) and there won't be any centralised caching.
