### ISSUE TITLE
uplinks use private registry

### ISSUE THREAD

**Issue by sunzongzheng** [rlidwka/sinopia#483]
How to config uplinks with private registry?

I hava an private registry on public internet, and now I want to make an copy in LAN. 

I have tried to modify the .npmrc on the server with sinopia, but it doesn't work.

When I run `npm i xxx`, I got 404 not find

**Comment by juanpicado** [comment]
The main registry (npmjs) should come by default enabled unless you have changed something in your conf. 

If you want to know more about uplinks 

https://www.verdaccio.org/docs/en/uplinks.html

**Comment by sunzongzheng** [comment]
I have resolved it by using verdaccio. thx

**Comment by juanpicado** [comment]
Good decision 😉👌🏼
