### ISSUE TITLE
.sinopia-db.json suddenly empty

### ISSUE THREAD

**Issue by rogierschouten** [rlidwka/sinopia#487]
After weeks of running fine, my v3 verdaccio docker container suddenly failed with the message that it could not parse .sinopia-db.json

Inspecting the JSON file revealed that it was suddenly empty.  Is there a way to re-generate this file from the rest of the registry content?

/edit:  and why is the file suddenly empty? Is this a known and fixed bug?  I guess I'm running a version below v3.1.0 but I stupidly used image verdaccio/verdaccio:3 in my docker-compose file so I can't be sure which it is.

**Comment by juanpicado** [comment]
@rogierschouten  😉  ---> https://github.com/verdaccio/verdaccio

**Comment by rogierschouten** [comment]
@juanpicado  thx ;)
