### ISSUE TITLE
How to install or publish restricted page?

### ISSUE THREAD

**Issue by ashley7070** [rlidwka/sinopia#62]
I have my admin user setup and the generated password in sinopia. How do I now install or publish a package?

Does npm use _auth and email from the .npmrc file? so is email=admin then?

**Comment by iclanzan** [comment]
I think the keyword is `$all`.

**Comment by rlidwka** [comment]
@iclanzan , it was `all` a year ago. I renamed it in `1.0.0` because of possible conflicts with real user names.
