### ISSUE TITLE
no access to public packages 

### ISSUE THREAD

**Issue by koraysels** [rlidwka/sinopia#97]
so I published my private package to my personal server and everything went OK. 

then i tried installing that package through that private registry but it failed to get all the public dependencies from npmjs.org. I get ```error: getaddrinfo ENOTFOUND```

what could be the cause of this ?

**Comment by rlidwka** [comment]
or DNS server is down

If anyone is having similar issues, `ping registry.npmjs.org` from the server sinopia is running on will provide a pretty clear picture of what's going on.
