### ISSUE TITLE
Is it possible to use sinopia in environment with no internet?

### ISSUE THREAD

**Issue by derkd** [rlidwka/sinopia#98]
I'm interested if it is possible to set up a private repo (sinopia) which has no connection to internet (policy)? Currently we pack our node_modules in a tar file and put them in SVN. Every build we unpack this tar. I tried to npm publish it to sinopia but it doesn't publish it's dependencies with it. Do I need to write a shell script which walks through the directories (of the dependencies) and search for a "node_modules" dir with a package.json and then do a npm publish every time? 
I'm quite a newbie on all this...

**Comment by ralberts** [comment]
So glad for this thread!  I was running into a similar problem as I will have no internet.  Thanks @njenia as I will test out your script and the other suggestions in this thread.

**Comment by njenia** [comment]
@ralberts The script is useful if you want all of the versions of relevant packages. But if you want to get a specific version of a package (and all of its dependencies) I found out that cleaning caches (of npm and sinopia) does the trick. It will get one tarball per each package, which is enough if you want only that specific version of a package.

**Comment by anitakrueger** [comment]
@rlidwka quick question if I may. I will have a VM with internet access running sinopia, but I don't want it to go out to the internet for packages, basically always using the local cache. I've removed all uplinks, but sinopia still goes out to registry.npmjs.org to download packages. Even if I make the uplink unusable (by making up a hostname that doesn't exist), sinopia will always fall back to contacting registry.npmjs.org for packages.
Is there a way to turn this off?

Thanks a lot
- Anita

**Comment by rlidwka** [comment]
@anitakrueger ,

> Even if I make the uplink unusable (by making up a hostname that doesn't exist), sinopia will always fall back to contacting registry.npmjs.org for packages.

There is no such fallback.

But it is possible that sinopia already fetched the metadata for some of the packages and stored information like "foobar@1.2.3 is located in registry.npmjs.org" for the particular versions of those packages.

Please check storage directory for sinopia and remove any unwanted packages from there.

**Comment by ghost** [comment]
As a complement to @njenia 's app, I also wrote a [small tool](https://github.com/g3ngar/sinopia-freeze-storage) that rewrites the storage files so the *repository latest* becomes the latest locally cached version in the storage. This is for avoiding downloading new versions if you already got the ones you needed. Hope it helps.
